use_frameworks!

platform :ios, '10.0'

target 'WifiTransferMusic_Example' do
  pod 'WifiTransferMusic', :path => '../'

  target 'WifiTransferMusic_Tests' do
    inherit! :search_paths

    
  end
end
